services:
  wordpress:
    image: wordpress:latest
    platform: linux/amd64
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      MYSQL_CLIENT_SSL: false
    volumes:
      - ./html:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db

  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - wordpress

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    ports:
      - "8025:8025"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
    depends_on:
      - db
  wpcli:
    image: wordpress:cli
    environment:
      MYSQL_CLIENT_SSL: false
    platform: linux/amd64
    volumes:
      - ./html:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - wordpress
    entrypoint: wp

volumes:
  db_data: